// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0qtWOar7JQ8JkMfIMFwmatBetXyJtAOw',
    appId: '1:853679004469:web:67f9965d73acf6e6ff0a7c',
    messagingSenderId: '853679004469',
    projectId: 'flutter-test-app-e9aae',
    authDomain: 'flutter-test-app-e9aae.firebaseapp.com',
    storageBucket: 'flutter-test-app-e9aae.appspot.com',
    measurementId: 'G-B1M7NC6GTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOZKkGdkVfWQsYwV5tC1eimqevBCogwO4',
    appId: '1:853679004469:android:381e806c1a4a7fb0ff0a7c',
    messagingSenderId: '853679004469',
    projectId: 'flutter-test-app-e9aae',
    storageBucket: 'flutter-test-app-e9aae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWp8mWi_jGPRbdPrGAcbB2AR5WHPrEgoo',
    appId: '1:853679004469:ios:8b8cc32e06649d8cff0a7c',
    messagingSenderId: '853679004469',
    projectId: 'flutter-test-app-e9aae',
    storageBucket: 'flutter-test-app-e9aae.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

}